# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true
  schema:gen:
    cmds:
      - buf generate
    silent: true
  server:build:
    cmds:
      - go build .
    dir: server
    silent: true
